spring:
  datasource:
    url: url
    username: root
    password: admin
  application:
    name: TestName
  main:
    banner-mode: off
  profiles:
    active: prod
server:
  port: 80
logging:
  level:
    root: error